// SPDX-License-Identifier: MIT
// Copyright 2025 RnD Center "ELVEES", JSC

#ifndef SSI0_DW_APB_SSI_REG_FIELDS_HPP
#define SSI0_DW_APB_SSI_REG_FIELDS_HPP

//this file was automatically generated, don't edit this file

#define MASK_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(max_, min_) \
	((max_ - min_) == 31 ? 0xFFFFFFFF : ((1 << (max_ - min_ + 1)) - 1))
#define SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, max_, min_) \
	(((a) & MASK_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(max_, min_)) << min_)
#define GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, max_, min_) \
	(((a) >> min_) & MASK_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(max_, min_))
#define SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, max_, min_)                    \
	(((reg) & (~(MASK_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(max_, min_) << min_))) | \
	 SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(f, max_, min_))

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_DFS      0
#define SSI0_DW_APB_SSI_CTRLR0_DFS(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 3, 0)
#define GET_SSI0_DW_APB_SSI_CTRLR0_DFS(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 3, 0)
#define SET_SSI0_DW_APB_SSI_CTRLR0_DFS(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 3, 0)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_FRF      4
#define SSI0_DW_APB_SSI_CTRLR0_FRF(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 4)
#define GET_SSI0_DW_APB_SSI_CTRLR0_FRF(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 4)
#define SET_SSI0_DW_APB_SSI_CTRLR0_FRF(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 5, 4)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_SCPH	6
#define SSI0_DW_APB_SSI_CTRLR0_SCPH(a)		SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 6, 6)
#define GET_SSI0_DW_APB_SSI_CTRLR0_SCPH(a)	GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 6, 6)
#define SET_SSI0_DW_APB_SSI_CTRLR0_SCPH(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 6, 6)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_SCPOL 7
#define SSI0_DW_APB_SSI_CTRLR0_SCPOL(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 7, 7)
#define GET_SSI0_DW_APB_SSI_CTRLR0_SCPOL(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 7, 7)
#define SET_SSI0_DW_APB_SSI_CTRLR0_SCPOL(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 7, 7)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_TMOD	8
#define SSI0_DW_APB_SSI_CTRLR0_TMOD(a)		SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 9, 8)
#define GET_SSI0_DW_APB_SSI_CTRLR0_TMOD(a)	GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 9, 8)
#define SET_SSI0_DW_APB_SSI_CTRLR0_TMOD(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 9, 8)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_RSVD_SLV_OE 10
#define SSI0_DW_APB_SSI_CTRLR0_RSVD_SLV_OE(a)	  SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 10, 10)
#define GET_SSI0_DW_APB_SSI_CTRLR0_RSVD_SLV_OE(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 10, 10)
#define SET_SSI0_DW_APB_SSI_CTRLR0_RSVD_SLV_OE(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 10, 10)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_SRL 11
#define SSI0_DW_APB_SSI_CTRLR0_SRL(a)	  SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 11, 11)
#define GET_SSI0_DW_APB_SSI_CTRLR0_SRL(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 11, 11)
#define SET_SSI0_DW_APB_SSI_CTRLR0_SRL(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 11, 11)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_CFS 12
#define SSI0_DW_APB_SSI_CTRLR0_CFS(a)	  SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 15, 12)
#define GET_SSI0_DW_APB_SSI_CTRLR0_CFS(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 15, 12)
#define SET_SSI0_DW_APB_SSI_CTRLR0_CFS(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 15, 12)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_DFS_32 16
#define SSI0_DW_APB_SSI_CTRLR0_DFS_32(a)     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 20, 16)
#define GET_SSI0_DW_APB_SSI_CTRLR0_DFS_32(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 20, 16)
#define SET_SSI0_DW_APB_SSI_CTRLR0_DFS_32(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 20, 16)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_SPI_FRF 21
#define SSI0_DW_APB_SSI_CTRLR0_SPI_FRF(a)     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 22, 21)
#define GET_SSI0_DW_APB_SSI_CTRLR0_SPI_FRF(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 22, 21)
#define SET_SSI0_DW_APB_SSI_CTRLR0_SPI_FRF(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 22, 21)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_RSVD_CTRLR0_23 23
#define SSI0_DW_APB_SSI_CTRLR0_RSVD_CTRLR0_23(a)     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 23, 23)
#define GET_SSI0_DW_APB_SSI_CTRLR0_RSVD_CTRLR0_23(a) \
	GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 23, 23)
#define SET_SSI0_DW_APB_SSI_CTRLR0_RSVD_CTRLR0_23(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 23, 23)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_SSTE 24
#define SSI0_DW_APB_SSI_CTRLR0_SSTE(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 24, 24)
#define GET_SSI0_DW_APB_SSI_CTRLR0_SSTE(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 24, 24)
#define SET_SSI0_DW_APB_SSI_CTRLR0_SSTE(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 24, 24)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR0_RSVD_CTRLR0 25
#define SSI0_DW_APB_SSI_CTRLR0_RSVD_CTRLR0(a)	  SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 25)
#define GET_SSI0_DW_APB_SSI_CTRLR0_RSVD_CTRLR0(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 25)
#define SET_SSI0_DW_APB_SSI_CTRLR0_RSVD_CTRLR0(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 25)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR1_NDF      0
#define SSI0_DW_APB_SSI_CTRLR1_NDF(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 15, 0)
#define GET_SSI0_DW_APB_SSI_CTRLR1_NDF(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 15, 0)
#define SET_SSI0_DW_APB_SSI_CTRLR1_NDF(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 15, 0)

#define OFFSET_SSI0_DW_APB_SSI_CTRLR1_RSVD_CTRLR1 16
#define SSI0_DW_APB_SSI_CTRLR1_RSVD_CTRLR1(a)	  SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 16)
#define GET_SSI0_DW_APB_SSI_CTRLR1_RSVD_CTRLR1(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 16)
#define SET_SSI0_DW_APB_SSI_CTRLR1_RSVD_CTRLR1(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 16)

#define OFFSET_SSI0_DW_APB_SSI_SSIENR_SSI_EN 0
#define SSI0_DW_APB_SSI_SSIENR_SSI_EN(a)     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define GET_SSI0_DW_APB_SSI_SSIENR_SSI_EN(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define SET_SSI0_DW_APB_SSI_SSIENR_SSI_EN(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 0, 0)

#define OFFSET_SSI0_DW_APB_SSI_SSIENR_RSVD_SSIENR 1
#define SSI0_DW_APB_SSI_SSIENR_RSVD_SSIENR(a)	  SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 1)
#define GET_SSI0_DW_APB_SSI_SSIENR_RSVD_SSIENR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 1)
#define SET_SSI0_DW_APB_SSI_SSIENR_RSVD_SSIENR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 1)

#define OFFSET_SSI0_DW_APB_SSI_MWCR_MWMOD      0
#define SSI0_DW_APB_SSI_MWCR_MWMOD(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define GET_SSI0_DW_APB_SSI_MWCR_MWMOD(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define SET_SSI0_DW_APB_SSI_MWCR_MWMOD(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 0, 0)

#define OFFSET_SSI0_DW_APB_SSI_MWCR_MDD	     1
#define SSI0_DW_APB_SSI_MWCR_MDD(a)	     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 1, 1)
#define GET_SSI0_DW_APB_SSI_MWCR_MDD(a)	     GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 1, 1)
#define SET_SSI0_DW_APB_SSI_MWCR_MDD(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 1, 1)

#define OFFSET_SSI0_DW_APB_SSI_MWCR_MHS	     2
#define SSI0_DW_APB_SSI_MWCR_MHS(a)	     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 2, 2)
#define GET_SSI0_DW_APB_SSI_MWCR_MHS(a)	     GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 2, 2)
#define SET_SSI0_DW_APB_SSI_MWCR_MHS(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 2, 2)

#define OFFSET_SSI0_DW_APB_SSI_MWCR_RSVD_MWCR 3
#define SSI0_DW_APB_SSI_MWCR_RSVD_MWCR(a)     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 3)
#define GET_SSI0_DW_APB_SSI_MWCR_RSVD_MWCR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 3)
#define SET_SSI0_DW_APB_SSI_MWCR_RSVD_MWCR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 3)

#define OFFSET_SSI0_DW_APB_SSI_SER_SER	    0
#define SSI0_DW_APB_SSI_SER_SER(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 3, 0)
#define GET_SSI0_DW_APB_SSI_SER_SER(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 3, 0)
#define SET_SSI0_DW_APB_SSI_SER_SER(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 3, 0)

#define OFFSET_SSI0_DW_APB_SSI_SER_RSVD_SER 4
#define SSI0_DW_APB_SSI_SER_RSVD_SER(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 4)
#define GET_SSI0_DW_APB_SSI_SER_RSVD_SER(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 4)
#define SET_SSI0_DW_APB_SSI_SER_RSVD_SER(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 4)

#define OFFSET_SSI0_DW_APB_SSI_BAUDR_SCKDV 0
#define SSI0_DW_APB_SSI_BAUDR_SCKDV(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 15, 0)
#define GET_SSI0_DW_APB_SSI_BAUDR_SCKDV(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 15, 0)
#define SET_SSI0_DW_APB_SSI_BAUDR_SCKDV(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 15, 0)

#define OFFSET_SSI0_DW_APB_SSI_BAUDR_RSVD_BAUDR 16
#define SSI0_DW_APB_SSI_BAUDR_RSVD_BAUDR(a)	SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 16)
#define GET_SSI0_DW_APB_SSI_BAUDR_RSVD_BAUDR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 16)
#define SET_SSI0_DW_APB_SSI_BAUDR_RSVD_BAUDR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 16)

#define OFFSET_SSI0_DW_APB_SSI_TXFTLR_TFT      0
#define SSI0_DW_APB_SSI_TXFTLR_TFT(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 0)
#define GET_SSI0_DW_APB_SSI_TXFTLR_TFT(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 0)
#define SET_SSI0_DW_APB_SSI_TXFTLR_TFT(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 5, 0)

#define OFFSET_SSI0_DW_APB_SSI_TXFTLR_RSVD_TXFTLR 6
#define SSI0_DW_APB_SSI_TXFTLR_RSVD_TXFTLR(a)	  SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define GET_SSI0_DW_APB_SSI_TXFTLR_RSVD_TXFTLR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define SET_SSI0_DW_APB_SSI_TXFTLR_RSVD_TXFTLR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 6)

#define OFFSET_SSI0_DW_APB_SSI_RXFTLR_RFT      0
#define SSI0_DW_APB_SSI_RXFTLR_RFT(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 0)
#define GET_SSI0_DW_APB_SSI_RXFTLR_RFT(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 0)
#define SET_SSI0_DW_APB_SSI_RXFTLR_RFT(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 5, 0)

#define OFFSET_SSI0_DW_APB_SSI_RXFTLR_RSVD_RXFTLR 6
#define SSI0_DW_APB_SSI_RXFTLR_RSVD_RXFTLR(a)	  SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define GET_SSI0_DW_APB_SSI_RXFTLR_RSVD_RXFTLR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define SET_SSI0_DW_APB_SSI_RXFTLR_RSVD_RXFTLR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 6)

#define OFFSET_SSI0_DW_APB_SSI_TXFLR_TXTFL	0
#define SSI0_DW_APB_SSI_TXFLR_TXTFL(a)		SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 6, 0)
#define GET_SSI0_DW_APB_SSI_TXFLR_TXTFL(a)	GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 6, 0)
#define SET_SSI0_DW_APB_SSI_TXFLR_TXTFL(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 6, 0)

#define OFFSET_SSI0_DW_APB_SSI_TXFLR_RSVD_TXFLR 7
#define SSI0_DW_APB_SSI_TXFLR_RSVD_TXFLR(a)	SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 7)
#define GET_SSI0_DW_APB_SSI_TXFLR_RSVD_TXFLR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 7)
#define SET_SSI0_DW_APB_SSI_TXFLR_RSVD_TXFLR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 7)

#define OFFSET_SSI0_DW_APB_SSI_RXFLR_RXTFL	0
#define SSI0_DW_APB_SSI_RXFLR_RXTFL(a)		SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 6, 0)
#define GET_SSI0_DW_APB_SSI_RXFLR_RXTFL(a)	GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 6, 0)
#define SET_SSI0_DW_APB_SSI_RXFLR_RXTFL(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 6, 0)

#define OFFSET_SSI0_DW_APB_SSI_RXFLR_RSVD_RXFLR 7
#define SSI0_DW_APB_SSI_RXFLR_RSVD_RXFLR(a)	SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 7)
#define GET_SSI0_DW_APB_SSI_RXFLR_RSVD_RXFLR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 7)
#define SET_SSI0_DW_APB_SSI_RXFLR_RSVD_RXFLR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 7)

#define OFFSET_SSI0_DW_APB_SSI_SR_BUSY	    0
#define SSI0_DW_APB_SSI_SR_BUSY(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define GET_SSI0_DW_APB_SSI_SR_BUSY(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define SET_SSI0_DW_APB_SSI_SR_BUSY(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 0, 0)

#define OFFSET_SSI0_DW_APB_SSI_SR_TFNF	    1
#define SSI0_DW_APB_SSI_SR_TFNF(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 1, 1)
#define GET_SSI0_DW_APB_SSI_SR_TFNF(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 1, 1)
#define SET_SSI0_DW_APB_SSI_SR_TFNF(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 1, 1)

#define OFFSET_SSI0_DW_APB_SSI_SR_TFE	   2
#define SSI0_DW_APB_SSI_SR_TFE(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 2, 2)
#define GET_SSI0_DW_APB_SSI_SR_TFE(a)	   GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 2, 2)
#define SET_SSI0_DW_APB_SSI_SR_TFE(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 2, 2)

#define OFFSET_SSI0_DW_APB_SSI_SR_RFNE	    3
#define SSI0_DW_APB_SSI_SR_RFNE(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 3, 3)
#define GET_SSI0_DW_APB_SSI_SR_RFNE(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 3, 3)
#define SET_SSI0_DW_APB_SSI_SR_RFNE(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 3, 3)

#define OFFSET_SSI0_DW_APB_SSI_SR_RFF	   4
#define SSI0_DW_APB_SSI_SR_RFF(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 4, 4)
#define GET_SSI0_DW_APB_SSI_SR_RFF(a)	   GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 4, 4)
#define SET_SSI0_DW_APB_SSI_SR_RFF(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 4, 4)

#define OFFSET_SSI0_DW_APB_SSI_SR_RSVD_TXE	5
#define SSI0_DW_APB_SSI_SR_RSVD_TXE(a)		SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 5)
#define GET_SSI0_DW_APB_SSI_SR_RSVD_TXE(a)	GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 5)
#define SET_SSI0_DW_APB_SSI_SR_RSVD_TXE(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 5, 5)

#define OFFSET_SSI0_DW_APB_SSI_SR_DCOL	    6
#define SSI0_DW_APB_SSI_SR_DCOL(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 6, 6)
#define GET_SSI0_DW_APB_SSI_SR_DCOL(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 6, 6)
#define SET_SSI0_DW_APB_SSI_SR_DCOL(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 6, 6)

#define OFFSET_SSI0_DW_APB_SSI_SR_RSVD_SR      7
#define SSI0_DW_APB_SSI_SR_RSVD_SR(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 7)
#define GET_SSI0_DW_APB_SSI_SR_RSVD_SR(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 7)
#define SET_SSI0_DW_APB_SSI_SR_RSVD_SR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 7)

#define OFFSET_SSI0_DW_APB_SSI_IMR_TXEIM      0
#define SSI0_DW_APB_SSI_IMR_TXEIM(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define GET_SSI0_DW_APB_SSI_IMR_TXEIM(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define SET_SSI0_DW_APB_SSI_IMR_TXEIM(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 0, 0)

#define OFFSET_SSI0_DW_APB_SSI_IMR_TXOIM      1
#define SSI0_DW_APB_SSI_IMR_TXOIM(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 1, 1)
#define GET_SSI0_DW_APB_SSI_IMR_TXOIM(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 1, 1)
#define SET_SSI0_DW_APB_SSI_IMR_TXOIM(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 1, 1)

#define OFFSET_SSI0_DW_APB_SSI_IMR_RXUIM      2
#define SSI0_DW_APB_SSI_IMR_RXUIM(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 2, 2)
#define GET_SSI0_DW_APB_SSI_IMR_RXUIM(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 2, 2)
#define SET_SSI0_DW_APB_SSI_IMR_RXUIM(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 2, 2)

#define OFFSET_SSI0_DW_APB_SSI_IMR_RXOIM      3
#define SSI0_DW_APB_SSI_IMR_RXOIM(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 3, 3)
#define GET_SSI0_DW_APB_SSI_IMR_RXOIM(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 3, 3)
#define SET_SSI0_DW_APB_SSI_IMR_RXOIM(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 3, 3)

#define OFFSET_SSI0_DW_APB_SSI_IMR_RXFIM      4
#define SSI0_DW_APB_SSI_IMR_RXFIM(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 4, 4)
#define GET_SSI0_DW_APB_SSI_IMR_RXFIM(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 4, 4)
#define SET_SSI0_DW_APB_SSI_IMR_RXFIM(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 4, 4)

#define OFFSET_SSI0_DW_APB_SSI_IMR_MSTIM      5
#define SSI0_DW_APB_SSI_IMR_MSTIM(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 5)
#define GET_SSI0_DW_APB_SSI_IMR_MSTIM(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 5)
#define SET_SSI0_DW_APB_SSI_IMR_MSTIM(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 5, 5)

#define OFFSET_SSI0_DW_APB_SSI_IMR_RSVD_IMR 6
#define SSI0_DW_APB_SSI_IMR_RSVD_IMR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define GET_SSI0_DW_APB_SSI_IMR_RSVD_IMR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define SET_SSI0_DW_APB_SSI_IMR_RSVD_IMR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 6)

#define OFFSET_SSI0_DW_APB_SSI_ISR_TXEIS      0
#define SSI0_DW_APB_SSI_ISR_TXEIS(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define GET_SSI0_DW_APB_SSI_ISR_TXEIS(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define SET_SSI0_DW_APB_SSI_ISR_TXEIS(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 0, 0)

#define OFFSET_SSI0_DW_APB_SSI_ISR_TXOIS      1
#define SSI0_DW_APB_SSI_ISR_TXOIS(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 1, 1)
#define GET_SSI0_DW_APB_SSI_ISR_TXOIS(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 1, 1)
#define SET_SSI0_DW_APB_SSI_ISR_TXOIS(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 1, 1)

#define OFFSET_SSI0_DW_APB_SSI_ISR_RXUIS      2
#define SSI0_DW_APB_SSI_ISR_RXUIS(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 2, 2)
#define GET_SSI0_DW_APB_SSI_ISR_RXUIS(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 2, 2)
#define SET_SSI0_DW_APB_SSI_ISR_RXUIS(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 2, 2)

#define OFFSET_SSI0_DW_APB_SSI_ISR_RXOIS      3
#define SSI0_DW_APB_SSI_ISR_RXOIS(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 3, 3)
#define GET_SSI0_DW_APB_SSI_ISR_RXOIS(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 3, 3)
#define SET_SSI0_DW_APB_SSI_ISR_RXOIS(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 3, 3)

#define OFFSET_SSI0_DW_APB_SSI_ISR_RXFIS      4
#define SSI0_DW_APB_SSI_ISR_RXFIS(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 4, 4)
#define GET_SSI0_DW_APB_SSI_ISR_RXFIS(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 4, 4)
#define SET_SSI0_DW_APB_SSI_ISR_RXFIS(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 4, 4)

#define OFFSET_SSI0_DW_APB_SSI_ISR_MSTIS      5
#define SSI0_DW_APB_SSI_ISR_MSTIS(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 5)
#define GET_SSI0_DW_APB_SSI_ISR_MSTIS(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 5)
#define SET_SSI0_DW_APB_SSI_ISR_MSTIS(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 5, 5)

#define OFFSET_SSI0_DW_APB_SSI_ISR_RSVD_ISR 6
#define SSI0_DW_APB_SSI_ISR_RSVD_ISR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define GET_SSI0_DW_APB_SSI_ISR_RSVD_ISR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define SET_SSI0_DW_APB_SSI_ISR_RSVD_ISR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 6)

#define OFFSET_SSI0_DW_APB_SSI_RISR_TXEIR      0
#define SSI0_DW_APB_SSI_RISR_TXEIR(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define GET_SSI0_DW_APB_SSI_RISR_TXEIR(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define SET_SSI0_DW_APB_SSI_RISR_TXEIR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 0, 0)

#define OFFSET_SSI0_DW_APB_SSI_RISR_TXOIR      1
#define SSI0_DW_APB_SSI_RISR_TXOIR(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 1, 1)
#define GET_SSI0_DW_APB_SSI_RISR_TXOIR(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 1, 1)
#define SET_SSI0_DW_APB_SSI_RISR_TXOIR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 1, 1)

#define OFFSET_SSI0_DW_APB_SSI_RISR_RXUIR      2
#define SSI0_DW_APB_SSI_RISR_RXUIR(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 2, 2)
#define GET_SSI0_DW_APB_SSI_RISR_RXUIR(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 2, 2)
#define SET_SSI0_DW_APB_SSI_RISR_RXUIR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 2, 2)

#define OFFSET_SSI0_DW_APB_SSI_RISR_RXOIR      3
#define SSI0_DW_APB_SSI_RISR_RXOIR(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 3, 3)
#define GET_SSI0_DW_APB_SSI_RISR_RXOIR(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 3, 3)
#define SET_SSI0_DW_APB_SSI_RISR_RXOIR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 3, 3)

#define OFFSET_SSI0_DW_APB_SSI_RISR_RXFIR      4
#define SSI0_DW_APB_SSI_RISR_RXFIR(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 4, 4)
#define GET_SSI0_DW_APB_SSI_RISR_RXFIR(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 4, 4)
#define SET_SSI0_DW_APB_SSI_RISR_RXFIR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 4, 4)

#define OFFSET_SSI0_DW_APB_SSI_RISR_MSTIR      5
#define SSI0_DW_APB_SSI_RISR_MSTIR(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 5)
#define GET_SSI0_DW_APB_SSI_RISR_MSTIR(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 5)
#define SET_SSI0_DW_APB_SSI_RISR_MSTIR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 5, 5)

#define OFFSET_SSI0_DW_APB_SSI_RISR_RSVD_RISR 6
#define SSI0_DW_APB_SSI_RISR_RSVD_RISR(a)     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define GET_SSI0_DW_APB_SSI_RISR_RSVD_RISR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define SET_SSI0_DW_APB_SSI_RISR_RSVD_RISR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 6)

#define OFFSET_SSI0_DW_APB_SSI_TXOICR_TXOICR 0
#define SSI0_DW_APB_SSI_TXOICR_TXOICR(a)     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define GET_SSI0_DW_APB_SSI_TXOICR_TXOICR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define SET_SSI0_DW_APB_SSI_TXOICR_TXOICR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 0, 0)

#define OFFSET_SSI0_DW_APB_SSI_TXOICR_RSVD_TXOICR 1
#define SSI0_DW_APB_SSI_TXOICR_RSVD_TXOICR(a)	  SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 1)
#define GET_SSI0_DW_APB_SSI_TXOICR_RSVD_TXOICR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 1)
#define SET_SSI0_DW_APB_SSI_TXOICR_RSVD_TXOICR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 1)

#define OFFSET_SSI0_DW_APB_SSI_RXOICR_RXOICR 0
#define SSI0_DW_APB_SSI_RXOICR_RXOICR(a)     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define GET_SSI0_DW_APB_SSI_RXOICR_RXOICR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define SET_SSI0_DW_APB_SSI_RXOICR_RXOICR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 0, 0)

#define OFFSET_SSI0_DW_APB_SSI_RXOICR_RSVD_RXOICR 1
#define SSI0_DW_APB_SSI_RXOICR_RSVD_RXOICR(a)	  SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 1)
#define GET_SSI0_DW_APB_SSI_RXOICR_RSVD_RXOICR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 1)
#define SET_SSI0_DW_APB_SSI_RXOICR_RSVD_RXOICR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 1)

#define OFFSET_SSI0_DW_APB_SSI_RXUICR_RXUICR 0
#define SSI0_DW_APB_SSI_RXUICR_RXUICR(a)     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define GET_SSI0_DW_APB_SSI_RXUICR_RXUICR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define SET_SSI0_DW_APB_SSI_RXUICR_RXUICR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 0, 0)

#define OFFSET_SSI0_DW_APB_SSI_RXUICR_RSVD_RXUICR 1
#define SSI0_DW_APB_SSI_RXUICR_RSVD_RXUICR(a)	  SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 1)
#define GET_SSI0_DW_APB_SSI_RXUICR_RSVD_RXUICR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 1)
#define SET_SSI0_DW_APB_SSI_RXUICR_RSVD_RXUICR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 1)

#define OFFSET_SSI0_DW_APB_SSI_MSTICR_MSTICR 0
#define SSI0_DW_APB_SSI_MSTICR_MSTICR(a)     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define GET_SSI0_DW_APB_SSI_MSTICR_MSTICR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define SET_SSI0_DW_APB_SSI_MSTICR_MSTICR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 0, 0)

#define OFFSET_SSI0_DW_APB_SSI_MSTICR_RSVD_MSTICR 1
#define SSI0_DW_APB_SSI_MSTICR_RSVD_MSTICR(a)	  SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 1)
#define GET_SSI0_DW_APB_SSI_MSTICR_RSVD_MSTICR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 1)
#define SET_SSI0_DW_APB_SSI_MSTICR_RSVD_MSTICR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 1)

#define OFFSET_SSI0_DW_APB_SSI_ICR_ICR	    0
#define SSI0_DW_APB_SSI_ICR_ICR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define GET_SSI0_DW_APB_SSI_ICR_ICR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define SET_SSI0_DW_APB_SSI_ICR_ICR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 0, 0)

#define OFFSET_SSI0_DW_APB_SSI_ICR_RSVD_ICR 1
#define SSI0_DW_APB_SSI_ICR_RSVD_ICR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 1)
#define GET_SSI0_DW_APB_SSI_ICR_RSVD_ICR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 1)
#define SET_SSI0_DW_APB_SSI_ICR_RSVD_ICR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 1)

#define OFFSET_SSI0_DW_APB_SSI_DMACR_RDMAE	0
#define SSI0_DW_APB_SSI_DMACR_RDMAE(a)		SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define GET_SSI0_DW_APB_SSI_DMACR_RDMAE(a)	GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 0, 0)
#define SET_SSI0_DW_APB_SSI_DMACR_RDMAE(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 0, 0)

#define OFFSET_SSI0_DW_APB_SSI_DMACR_TDMAE	1
#define SSI0_DW_APB_SSI_DMACR_TDMAE(a)		SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 1, 1)
#define GET_SSI0_DW_APB_SSI_DMACR_TDMAE(a)	GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 1, 1)
#define SET_SSI0_DW_APB_SSI_DMACR_TDMAE(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 1, 1)

#define OFFSET_SSI0_DW_APB_SSI_DMACR_RSVD_DMACR 2
#define SSI0_DW_APB_SSI_DMACR_RSVD_DMACR(a)	SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 2)
#define GET_SSI0_DW_APB_SSI_DMACR_RSVD_DMACR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 2)
#define SET_SSI0_DW_APB_SSI_DMACR_RSVD_DMACR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 2)

#define OFFSET_SSI0_DW_APB_SSI_DMATDLR_DMATDL 0
#define SSI0_DW_APB_SSI_DMATDLR_DMATDL(a)     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 0)
#define GET_SSI0_DW_APB_SSI_DMATDLR_DMATDL(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 0)
#define SET_SSI0_DW_APB_SSI_DMATDLR_DMATDL(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 5, 0)

#define OFFSET_SSI0_DW_APB_SSI_DMATDLR_RSVD_DMATDLR 6
#define SSI0_DW_APB_SSI_DMATDLR_RSVD_DMATDLR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define GET_SSI0_DW_APB_SSI_DMATDLR_RSVD_DMATDLR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define SET_SSI0_DW_APB_SSI_DMATDLR_RSVD_DMATDLR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 6)

#define OFFSET_SSI0_DW_APB_SSI_DMARDLR_DMARDL 0
#define SSI0_DW_APB_SSI_DMARDLR_DMARDL(a)     SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 0)
#define GET_SSI0_DW_APB_SSI_DMARDLR_DMARDL(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 5, 0)
#define SET_SSI0_DW_APB_SSI_DMARDLR_DMARDL(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 5, 0)

#define OFFSET_SSI0_DW_APB_SSI_DMARDLR_RSVD_DMARDLR 6
#define SSI0_DW_APB_SSI_DMARDLR_RSVD_DMARDLR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define GET_SSI0_DW_APB_SSI_DMARDLR_RSVD_DMARDLR(a) GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 6)
#define SET_SSI0_DW_APB_SSI_DMARDLR_RSVD_DMARDLR(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 6)

#define OFFSET_SSI0_DW_APB_SSI_IDR_IDCODE      0
#define SSI0_DW_APB_SSI_IDR_IDCODE(a)	       SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_IDR_IDCODE(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_IDR_IDCODE(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_SSI_VERSION_ID_SSI_COMP_VERSION 0
#define SSI0_DW_APB_SSI_SSI_VERSION_ID_SSI_COMP_VERSION(a) \
	SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_SSI_VERSION_ID_SSI_COMP_VERSION(a) \
	GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_SSI_VERSION_ID_SSI_COMP_VERSION(reg, f) \
	SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR0_DR	   0
#define SSI0_DW_APB_SSI_DR0_DR(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR0_DR(a)	   GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR0_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR1_DR	   0
#define SSI0_DW_APB_SSI_DR1_DR(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR1_DR(a)	   GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR1_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR2_DR	   0
#define SSI0_DW_APB_SSI_DR2_DR(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR2_DR(a)	   GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR2_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR3_DR	   0
#define SSI0_DW_APB_SSI_DR3_DR(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR3_DR(a)	   GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR3_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR4_DR	   0
#define SSI0_DW_APB_SSI_DR4_DR(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR4_DR(a)	   GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR4_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR5_DR	   0
#define SSI0_DW_APB_SSI_DR5_DR(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR5_DR(a)	   GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR5_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR6_DR	   0
#define SSI0_DW_APB_SSI_DR6_DR(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR6_DR(a)	   GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR6_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR7_DR	   0
#define SSI0_DW_APB_SSI_DR7_DR(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR7_DR(a)	   GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR7_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR8_DR	   0
#define SSI0_DW_APB_SSI_DR8_DR(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR8_DR(a)	   GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR8_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR9_DR	   0
#define SSI0_DW_APB_SSI_DR9_DR(a)	   SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR9_DR(a)	   GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR9_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR10_DR	    0
#define SSI0_DW_APB_SSI_DR10_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR10_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR10_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR11_DR	    0
#define SSI0_DW_APB_SSI_DR11_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR11_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR11_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR12_DR	    0
#define SSI0_DW_APB_SSI_DR12_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR12_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR12_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR13_DR	    0
#define SSI0_DW_APB_SSI_DR13_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR13_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR13_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR14_DR	    0
#define SSI0_DW_APB_SSI_DR14_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR14_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR14_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR15_DR	    0
#define SSI0_DW_APB_SSI_DR15_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR15_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR15_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR16_DR	    0
#define SSI0_DW_APB_SSI_DR16_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR16_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR16_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR17_DR	    0
#define SSI0_DW_APB_SSI_DR17_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR17_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR17_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR18_DR	    0
#define SSI0_DW_APB_SSI_DR18_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR18_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR18_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR19_DR	    0
#define SSI0_DW_APB_SSI_DR19_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR19_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR19_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR20_DR	    0
#define SSI0_DW_APB_SSI_DR20_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR20_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR20_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR21_DR	    0
#define SSI0_DW_APB_SSI_DR21_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR21_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR21_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR22_DR	    0
#define SSI0_DW_APB_SSI_DR22_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR22_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR22_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR23_DR	    0
#define SSI0_DW_APB_SSI_DR23_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR23_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR23_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR24_DR	    0
#define SSI0_DW_APB_SSI_DR24_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR24_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR24_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR25_DR	    0
#define SSI0_DW_APB_SSI_DR25_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR25_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR25_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR26_DR	    0
#define SSI0_DW_APB_SSI_DR26_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR26_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR26_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR27_DR	    0
#define SSI0_DW_APB_SSI_DR27_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR27_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR27_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR28_DR	    0
#define SSI0_DW_APB_SSI_DR28_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR28_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR28_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR29_DR	    0
#define SSI0_DW_APB_SSI_DR29_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR29_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR29_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR30_DR	    0
#define SSI0_DW_APB_SSI_DR30_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR30_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR30_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR31_DR	    0
#define SSI0_DW_APB_SSI_DR31_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR31_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR31_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR32_DR	    0
#define SSI0_DW_APB_SSI_DR32_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR32_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR32_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR33_DR	    0
#define SSI0_DW_APB_SSI_DR33_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR33_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR33_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR34_DR	    0
#define SSI0_DW_APB_SSI_DR34_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR34_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR34_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_DR35_DR	    0
#define SSI0_DW_APB_SSI_DR35_DR(a)	    SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_DR35_DR(a)	    GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_DR35_DR(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#define OFFSET_SSI0_DW_APB_SSI_RSVD_RSVD      0
#define SSI0_DW_APB_SSI_RSVD_RSVD(a)	      SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define GET_SSI0_DW_APB_SSI_RSVD_RSVD(a)      GET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(a, 31, 0)
#define SET_SSI0_DW_APB_SSI_RSVD_RSVD(reg, f) SET_SSI0_DW_APB_SSI_REG_FIELDS_H_FIELD(reg, f, 31, 0)

#endif
